GET http://localhost:3001/api/notes
###
GET http://localhost:3001/api/notes/64787108c7b6bd757fafb131
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Yet another note",
    "important":false
}
###
PUT http://localhost:3001/api/notes/64787108c7b6bd757fafb131
Content-Type: application/json

{
    "important":false
}
###
DELETE http://localhost:3001/api/notes/647870ffc7b6bd757fafb12f