GET http://localhost:3001/api/notes
###
GET http://localhost:3001/api/notes/64785c8547808cec9244dcaa
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Yet another note",
    "important":false,
    "userId": "648c67577402aa84600b1800"
}
###
PUT http://localhost:3001/api/notes/64785c8547808cec9244dcaa
Content-Type: application/json

{
    "content": "Yet another",
    "important":true
}
###
DELETE http://localhost:3001/api/notes/64770631df0e46adb2c22279